FROM python:3.7.9
WORKDIR /home/ws

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

COPY requirements.txt /home/ws/requirements.txt
RUN pip install -r requirements.txt

COPY . /home/ws