version: '3.3'
services:
  django:
    build: .
    command: gunicorn AllProject.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - .env.example
    volumes:
      - static_volume:/home/app/django/static
      - media_volume:/home/app/django/media
    depends_on:
      - db
  daphne:
    build:
      context: ./
      dockerfile: Dockerfile_websocket
    command: daphne -b 0.0.0.0 -p 4154 AllProject.asgi:application
    env_file:
      - .env.example
    depends_on:
      - db
    expose:
      - 4154
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db.example
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/django/static
      - media_volume:/home/app/django/media
    ports:
      - 80:80
    depends_on:
      - django
      - daphne
  redis:
    image: redis:latest
    expose:
      - 6379
volumes:
  postgres_data:
  static_volume:
  media_volume: